name: demo_shorebird
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shorebird_code_push: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
